### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [dkarpele/notifications_sprint_1#8]
Несколько советов:
1. Вот это лишнее в проде:
https://github.com/dkarpele/notifications_sprint_1/blob/ea00e105af82dba28c4496f4f5e9fc45c362b071/docker-compose.yml#L27
2. Обратите внимание на вот это https://pheanex.github.io/pylint/. Подобных ошибок в коде много :(
3. Все настройки должны хранится в отдельном модуле/файле (config.py, settings.py ...). Нельзя разбрасывать настройки по разным модулям. Представь, что коллеге нужно будет поменять название переменной окружения - если нет файла с настройками, нужно открывать все модули и смотреть, не используется ли где-то эта переменная. Такой подход не верный. Если же настройки хранятся в одном файле, то их легко поддерживать, изменять и откатывать изменения, если что-то пошло не так.
Перенесите, пожалуйста, инициализацию переменных в файл с настройками. [Пример](https://github.com/dkarpele/notifications_sprint_1/blob/ea00e105af82dba28c4496f4f5e9fc45c362b071/notifications/src/smtp/send_emails.py#L79), [еще один](https://github.com/dkarpele/notifications_sprint_1/blob/ea00e105af82dba28c4496f4f5e9fc45c362b071/notifications/src/smtp/send_emails.py#L84) и [еще](https://github.com/dkarpele/notifications_sprint_1/blob/ea00e105af82dba28c4496f4f5e9fc45c362b071/notifications/src/db/postgres.py#L16).
4. [можно лучше] Не планируете сделать CRUD шаблонов сообщений? Это будет удобней, чем сейчас они просто в виде html файлов.
5. Эндпоинте user_welcome можно сделать немного более универсальным (см. п.7)
6. Весь сервис нотификации у вас жестко завязан с email сообщениями. Необходимо предусмотреть и другие способы связи с пользователями. Реализация не нужна, но подготовка в виде абстрактных классов и полей в моделях должна быть.
7. Но не смог найти какой-либо реализации (API эндпоинт или gRPC) следующего момента. Другие сервисы кинотеатра будут обращаться к сервису нотификации для того или иного уведомления пользователя.
Вот ситуация: в сервисе UGC появился новый комментарий к рецензии пользователя, и сервис UGC просит сервис нотификации уведомить пользователя об этом событии.
Другие сервисы кинотеатра, которые будут взаимодействовать с этим сервисом уведомлений, не будут иметь полной и актуальной информации о пользователе. У них точно будет id пользователя, а сервис нотификации, должен сходить в сервис авторизации (где у нас лежат актуальные данные пользователя).
8. [можно лучше] Пользователю может быть интересно получать уведомления списком в личном кабинете. Если, например, пропустил сообщение, то зашел в кабинет и все прочитал спокойно.

**Comment by dkarpele** [comment]
> [можно лучше] Не планируете сделать CRUD шаблонов сообщений? Это будет удобней, чем сейчас они просто в виде html файлов.

Посоветовались с наствником. 
"Ну, я знаю что я бы ответил, просто круд шаблонов не решает задачу удобного редактирования шаблонов, а давать такой шаткий инструмент, без контроля и версионности, проверки контекстных переменных и прочего, выглядит пустой тратой сил, я планирую что на первых этапах шаблоны преобразуются и добавляются программистом."

С нашей стороны пока также не видим смысла переносить это из репозитория.

**Comment by dkarpele** [comment]
> Но не смог найти какой-либо реализации (API эндпоинт или gRPC) следующего момента. 

Метод `/api/v1/users_unauth/user_ids` в сервисе auth
https://github.com/dkarpele/notifications_sprint_1/blob/main/notifications/src/schedule/notifications.py#L80

```python
   """
    API /api/v1/users_unauth/user_ids returns:
    [
    {
        "first_name": "admin",
        "last_name": "admin",
        "email": "admin@example.com",
        "id": "00791e6e-638e-4dcd-beee-15d6f1bf4571",
        "disabled": false,
        "is_admin": true,
        "roles": []
    }
    ]
    """
    url = f'http://{conf.settings.host_auth}:' \
          f'{conf.settings.port_auth}' \
          f'/api/v1/users_unauth/user_ids'
    user_ids_list: list = list(data_likes.keys())
    data_users: list = await api_post_helper(url, user_ids_list)

```

**Comment by BigDeepBlue** [comment]
> > 4. [можно лучше] Не планируете сделать CRUD шаблонов сообщений? Это будет удобней, чем сейчас они просто в виде html файлов.
> 
> Посоветовались с наставником. "Ну, я знаю что я бы ответил, просто круд шаблонов не решает задачу удобного редактирования шаблонов, а давать такой шаткий инструмент, без контроля и версионности, проверки контекстных переменных и прочего, выглядит пустой тратой сил, я планирую что на первых этапах шаблоны преобразуются и добавляются программистом."
> 
> С нашей стороны пока также не видим смысла переносить это из репозитория.

ок. Принимается.
Однако, когда проект станет глобальным и у вас будут шаблоны для всех праздников, времен года и прочего. Тогда разработчики сами будут настаивать, на том, чтобы вынести управление шаблонами в админку.

**Comment by BigDeepBlue** [comment]
LGTM
